### ISSUE TITLE
Unhandled exception takes out the process...

### ISSUE THREAD

**Issue by tomcarver** [canderso/Mixpanel#4]
Sorry to post a cryptic issue but I can't really follow where the problem is... it's only happened once, the rest of the time everything works fine, but killing the process does make you sit up and take notice:

On one occasion immediately after calling `MixpanelClient.GetCurrentClient()`, the following exception occurred. The exception bubbles all the way to `ThreadPoolWorkQueue` without being handled and this takes out the whole process.

    System.IO.IsolatedStorage.IsolatedStorageException: Unable to create the store directory. (Exception from HRESULT: 0x80131468)
    at System.IO.IsolatedStorage.IsolatedStorageFile.GetRootDir(IsolatedStorageScope scope, StringHandleOnStack retRootDir)
    at System.IO.IsolatedStorage.IsolatedStorageFile.InitGlobalsNonRoamingUser(IsolatedStorageScope scope)
    at System.IO.IsolatedStorage.IsolatedStorageFile.GetRootDir(IsolatedStorageScope scope)
    at System.IO.IsolatedStorage.IsolatedStorageFile.GetGlobalFileIOPerm(IsolatedStorageScope scope)
    at System.IO.IsolatedStorage.IsolatedStorageFile.Init(IsolatedStorageScope scope)
    at System.IO.IsolatedStorage.IsolatedStorageFile.GetStore(IsolatedStorageScope scope, Type domainEvidenceType, Type assemblyEvidenceType)
    at Mixpanel.MixpanelClient.TrySendLocalElements()
    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
    at System.Threading.ThreadPoolWorkQueue.Dispatch()

The hard disk has multiple GB free and I can't find any clues in the IsolatedStorage docs or forum posts about how this could occur sometimes and not others - it feels like an "always" or "never" error frankly.... but it definitely happened so I thought I'd post it here.

Judging by the timestamps on the latest revision I'm not expecting an immediate fix, but hopefully documenting the issue here can save someone else some time.

**Comment by petterh** [comment]
[This SO thread seems relevant](https://stackoverflow.com/questions/1035576/isolatedstorageexception-unable-to-create-the-store-directory).

**Comment by tomcarver** [comment]
Thanks for the reply! Yeah I'd found this thread before. If I got this exception on every call to `MixpanelClient.GetCurrentClient()` then I'd agree, account permissions could explain it. But this code has run without error for a few weeks before throwing the exception with no change to the environment or any of the user accounts, and every call to the API is prompted by the same route into the application (HTTP request to Nancy).
